# Curated default Dudley workstation profile
tap "brunoborges/tap"
tap "buildpacks/tap"
tap "joshyorko/tools"
tap "k0sproject/tap"
tap "ublue-os/tap"
tap "valkyrie00/bbrew"

# Terminal, shell, and common workstation tools
brew "ansible"
brew "atuin"
brew "awscli"
brew "bash-preexec"
brew "bat"
brew "brunoborges/tap/ghx"
brew "buildpacks/tap/pack"
brew "chezmoi"
brew "dialog"
brew "direnv"
brew "dysk"
brew "eza"
brew "fd"
brew "figlet"
brew "git-lfs"
brew "glab"
brew "mise"
brew "pigz"
brew "ripgrep"
brew "rtk"
brew "shellcheck"
brew "starship"
brew "stress-ng"
brew "tealdeer"
brew "television"
brew "trash-cli"
brew "tree"
brew "ugrep"
brew "unzip"
brew "uutils-coreutils"
brew "valkyrie00/bbrew/bbrew"
brew "yamllint"
brew "yq"
brew "zopfli"
brew "zoxide"

# Development and editor tooling
brew "devcontainer"
brew "helix"
brew "micro"
brew "node"
brew "nvim"
brew "python@3.13"
brew "python@3.14"
brew "uv"

# Kubernetes, containers, packaging, and security
brew "cdk8s"
brew "dagger"
brew "grype"
brew "hadolint"
brew "helm"
brew "k0sproject/tap/k0sctl"
brew "k3sup"
brew "k9s"
brew "kind"
brew "kubectx"
brew "kubernetes-cli"
brew "rancher-cli"
brew "syft"
brew "trivy"

# Josh's everyday tools
brew "joshyorko/tools/camp"
brew "joshyorko/tools/codex-release"
brew "joshyorko/tools/devpod-appindicator-runtime-tools"
brew "joshyorko/tools/devsy"
brew "joshyorko/tools/fizzy-cli-master"

cask "font-0xproto-nerd-font"
cask "font-blex-mono-nerd-font"
cask "font-caskaydia-mono-nerd-font"
cask "font-comic-shanns-mono-nerd-font"
cask "font-droid-sans-mono-nerd-font"
cask "font-fira-code-nerd-font"
cask "font-go-mono-nerd-font"
cask "font-jetbrains-mono-nerd-font"
cask "font-sauce-code-pro-nerd-font"
cask "font-source-code-pro"
cask "font-ubuntu-nerd-font"
cask "joshyorko/tools/action-server"
cask "joshyorko/tools/devpod-linux"
cask "joshyorko/tools/devsy-desktop"
cask "joshyorko/tools/rcc"
cask "joshyorko/tools/vscode-insiders-linux"
cask "ublue-os/tap/jetbrains-toolbox-linux"
cask "ublue-os/tap/visual-studio-code-linux"
cask "ublue-os/tap/vscodium-linux"
